
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans.eot
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans.eot?#iefix
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans.woff
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans.ttf
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans.svg#ywftsvg
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans-medium.eot
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans-medium.eot?#iefix
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans-medium.woff
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans-medium.ttf
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans-medium.svg#ywftsvg
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans-light.eot
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans-light.eot?#iefix
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans-light.woff
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans-light.ttf
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans-light.svg#ywftsvg
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans-regular-italic.eot
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans-regular-italic.eot?#iefix
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans-regular-italic.woff
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans-regular-italic.ttf
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans-regular-italic.svg#ywftsvg
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans-bold-italic.eot
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans-bold-italic.eot?#iefix
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans-bold-italic.woff
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans-bold-italic.ttf
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans-bold-italic.svg#ywftsvg
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans-bold.eot
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans-bold.eot?#iefix
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans-bold.woff
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans-bold.ttf
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans-bold.svg#ywftsvg
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans-thin.eot
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans-thin.eot?#iefix
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans-thin.woff
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans-thin.ttf
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans-thin.svg#ywftsvg
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans-light-italic.eot
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans-light-italic.eot?#iefix
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans-light-italic.woff
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans-light-italic.ttf
wget http://store.akamai.steamstatic.com/public/shared/fonts/motiva-sans-light-italic.svg#ywftsvg

pause